export const makerCheckerModules = [
  {
    id: "MC001",
    module: "User Management",
    operation: "Create User",
    description: "Requires checker approval before a new user is created.",
    enabled: true,
    lastModified: "2026-06-28 14:30:00",
    modifiedBy: "Priya Gupta",
  },
  {
    id: "MC002",
    module: "User Management",
    operation: "Edit User",
    description: "Requires checker approval before user details are updated.",
    enabled: true,
    lastModified: "2026-06-28 14:30:00",
    modifiedBy: "Priya Gupta",
  },
  {
    id: "MC003",
    module: "User Management",
    operation: "Delete User",
    description: "Requires checker approval before a user account is removed.",
    enabled: true,
    lastModified: "2026-06-25 11:15:00",
    modifiedBy: "Neha Singh",
  },
  {
    id: "MC004",
    module: "Role Management",
    operation: "Manage Roles",
    description: "Requires checker approval for role create, edit, or delete.",
    enabled: true,
    lastModified: "2026-06-22 09:45:00",
    modifiedBy: "Rahul Sharma",
  },
  {
    id: "MC005",
    module: "Role Management",
    operation: "Role Permission Mapping",
    description: "Requires checker approval before permission mappings are saved.",
    enabled: false,
    lastModified: "2026-06-20 16:20:00",
    modifiedBy: "Amit Patel",
  },
  {
    id: "MC006",
    module: "Institution Management",
    operation: "Institution Setup",
    description: "Requires checker approval for institution create or update.",
    enabled: true,
    lastModified: "2026-06-18 10:00:00",
    modifiedBy: "Vikram Desai",
  },
  {
    id: "MC007",
    module: "Institution Management",
    operation: "ACS URL Configuration",
    description: "Requires checker approval before ACS URL changes are applied.",
    enabled: true,
    lastModified: "2026-06-15 13:40:00",
    modifiedBy: "Sneha Reddy",
  },
  {
    id: "MC008",
    module: "Card Management",
    operation: "Block / Unblock Card",
    description: "Requires checker approval before card status is changed.",
    enabled: true,
    lastModified: "2026-06-12 08:55:00",
    modifiedBy: "Karan Mehta",
  },
  {
    id: "MC009",
    module: "Batch",
    operation: "Batch Configuration",
    description: "Requires checker approval before batch job settings are updated.",
    enabled: false,
    lastModified: "2026-06-10 17:30:00",
    modifiedBy: "Anita Joshi",
  },
  {
    id: "MC010",
    module: "System Management",
    operation: "HSM Configuration",
    description: "Requires checker approval before HSM settings are modified.",
    enabled: true,
    lastModified: "2026-06-08 12:10:00",
    modifiedBy: "Priya Gupta",
  },
];
